In [1]:
import numpy as np



In [3]:
a=np.random.randn(4,3) # a.shape = (4, 3)a.shape=(4,3)

b = np.random.randn(3,2) # b.shape = (3, 2)b.shape=(3,2)

c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [5]:
# a.shape = (3,4)a.shape=(3,4)

# b.shape = (4,1)b.shape=(4,1)
a=np.random.randn(3,4) 

b = np.random.randn(4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

NameError: name 'c' is not defined

In [17]:
a = np.random.randn(5)

In [18]:
print(a)

[ 0.18507851  0.31785562  0.25794839 -0.06245111 -0.75330592]


In [19]:
a.shape

(5,)

In [20]:
a.T

array([ 0.18507851,  0.31785562,  0.25794839, -0.06245111, -0.75330592])

In [21]:
print(np.dot(a,a.T))

0.7731935793920296


In [22]:
a = a.reshape(5,1)

In [23]:
a

array([[ 0.18507851],
       [ 0.31785562],
       [ 0.25794839],
       [-0.06245111],
       [-0.75330592]])

In [25]:
a.T

array([[ 0.18507851,  0.31785562,  0.25794839, -0.06245111, -0.75330592]])

In [27]:
a*a

array([[0.03425406],
       [0.1010322 ],
       [0.06653737],
       [0.00390014],
       [0.56746982]])

In [24]:
print(np.dot(a,a.T))

[[ 0.03425406  0.05882824  0.0477407  -0.01155836 -0.13942074]
 [ 0.05882824  0.1010322   0.08199034 -0.01985044 -0.23944252]
 [ 0.0477407   0.08199034  0.06653737 -0.01610916 -0.19431405]
 [-0.01155836 -0.01985044 -0.01610916  0.00390014  0.04704479]
 [-0.13942074 -0.23944252 -0.19431405  0.04704479  0.56746982]]
